### ISSUE TITLE
[Issue]PvCollects - Saving from DataTable

### ISSUE THREAD

**Issue by secret-dev87** [secret-dev87/windows-pathway#10]
Unfortunately the Loader still throws an error
Table PvCollects :Exception of type 'System.Exception' was thrown.

It did go past the previous step. This time the exception is when it is trying to insert the data. The datatable is populated with the correct data. But when writing to the database it throws the exception.

I noticed that the code in InsertEntityData (windows-pathway\Pathway\Pathway\Helper\MySQLHelper.cs::InsertEntityData) is still the MySQL specific one. You may need to convert that. Please do look into it and let us know.

**Comment by secret-dev87** [comment]
System.NotSupportedException
  HResult=0x80131515
  Message=To use MySqlBulkLoader.Local=true, set AllowLoadLocalInfile=true in the connection string. See https://fl.vu/mysql-load-data
  Source=MySqlConnector
  StackTrace:
   at MySqlConnector.MySqlBulkLoader.<LoadAsync>d__73.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.MySqlBulkLoader.Load()
   at Pathway.Core.Helper.MySQLHelper.InsertEntityData(String tableName, DataTable dsData, String path) in E:\03_work\windows-pathway\Pathway\Pathway\Helper\MySQLHelper.cs:line 193

  This exception was originally thrown at this call stack:
    [External Code]
    Pathway.Core.Helper.MySQLHelper.InsertEntityData(string, System.Data.DataTable, string) in MySQLHelper.cs

**Comment by secret-dev87** [comment]
Fixed this issue.
